### ISSUE TITLE
Improve the rudimentary illusts browser made for TeachingFeeling

### ISSUE THREAD

**Issue by yk0242** [yk0242/incubation#43]
su1302451
・初版

とある五月な掲示板で素敵なコードを拾ったので、ちょっと弄ってみる。
JS/HTML/CSSのお勉強を兼ねて。

主な目的：
* 背景も欲しいな…
* 他の場面も見たいな…
* 設定変更をもっと楽にしたいな…
* 最終的にはナデナデシテーもいいね…
* 当然製品版を前提とするよね…
  * 画像ファイルが必要だから自ずとそうなる
  * 出来れば製品版でしかないファイルとかセーブディレクトリの存在確認を入れたいな…（とりあえず諦めた）

作業方針：
* まずリファクタしてクラス構造化、他シーンの追加を容易にする。
* 背景欲しいね…
  * オフセット入れないと…
  * CSSめどいけど必要よね…
* 設定画面…
  * 場面変更は絶対必要
  * リロード時間動的に弄りたい
  * 背景非表示とか欲しいかも
* 本編に近い形にしたいからコード軽くなぞるね
* とりあえずChrome IE Fx は動作確認する

こ こ ま で や っ た 
何で今…

ファイル自体はまだ迷っているのでとりあえずGitHubには上げないでローカルgitのみでの運用で。

**Comment by yk0242** [comment]
ver.1.02
指定ディレクトリ配下のファイルリストとか、ファイル読込とか、純JSじゃ難しい？諦めた。
各レイヤーセレクタだけ追加。やっつけスパゲッティ－。

**Comment by FredCoder** [comment]
0口0，TeachingFeeling的编辑器。咱发现了不得了的东西了。。

**Comment by yk0242** [comment]
@FredCoder 
Not quite an editor, since it wasn't customized to the extent to allow for "edits" via external files or input or such... 
Only did what you can do within the game itself, save the huge overhead, for your parallel web-browsing-and-Sylvie-watching pleasures...

I personally prefer the in-game editable version in #45 .

**Comment by yk0242** [comment]
Migrate to Bitbucket. 
https://bitbucket.org/yk0242/teachingfeeling-related/issues/1/
